version: "3"
services:
  django_app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./PaymentProject:/PaymentProject
  celery:
    image: celery:3.1
    container_name: celery
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A PaymentProject worker -l INFO
    volumes:
      - .:/PaymentProject
    depends_on:
      - redis
      - mongodb
      - django_app
    links:
      - mongodb
      - redis
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis